name: quran_app
description: Quran app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

dependency_overrides:
  test_api: ^0.4.17

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sources/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: IsepMisbah
      fonts:
        - asset: assets/fonts/isepMisbah.ttf
