name: quran_app
description: Quran app
version: 2.2.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  adhan: ^2.0.0+1
  bloc: ^9.0.1
  date_picker_timeline: ^1.2.3
  equatable: ^2.0.5
  feedback: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_email_sender: ^8.0.0
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  flutter_qiblah: ^3.1.0+1
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.2.1
  flutter_timezone: ^5.0.0
  geocoding: ^4.0.0
  geolocator: ^13.0.4
  get_it: ^8.2.0
  intl: ^0.20.2
  just_audio: ^0.10.5
  # notification_permissions: ^0.6.1 - Removed in favor of permission_handler
  path: ^1.9.0
  path_provider: ^2.0.12
  permission_handler: ^12.0.1
  scrollable_positioned_list: ^0.3.5
  skeletonizer: ^2.1.0+1
  sqflite: ^2.3.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.9.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/launcher.png"
  min_sdk_android: 20
  adaptive_icon_background: "#234D60"
  adaptive_icon_foreground: "assets/launcher_icon/icon_adaptive.png"

flutter_native_splash:
  color: "#244C64"
  image: assets/launcher_icon/launcher.png

  android_12:
    image: assets/launcher_icon/launcher.png
    icon_background_color: "#244C64"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sources/
    - assets/icons/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: isepMisbah
      fonts:
        - asset: assets/fonts/isepMisbah.ttf
    - family: DsDigital
      fonts:
        - asset: assets/fonts/dsdigi.ttf
