name: single_radio
description: Single channel radio player.
publish_to: 'none'
version: 2.4.0+41

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  #firebase_core: 4.1.0
  #firebase_messaging: 16.0.1
  #flutter_local_notifications: 19.4.2
  #google_mobile_ads: 6.0.0
  provider: 6.1.5
  http: 1.5.0
  share_plus: 12.0.0
  in_app_review: 2.0.11
  flutter_markdown: 0.7.7
  flutter_svg: 2.2.1
  url_launcher: 6.3.2
  text_scroll: 0.2.1
  sleek_circular_slider : 2.1.0
  radio_player: 1.7.1
  volume_regulator: 2.4.2
  android_minimizer: 1.1.0

dev_dependencies:
  flutter_lints: 5.0.0
  flutter_launcher_icons: 0.14.3
  flutter_native_splash: 2.4.6
  change_app_package_name: 1.5.0

flutter_icons:
  image_path: "assets/appicon/appicon.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/appicon/appicon-adaptive.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#172230"
  image: assets/splash/splash.png
  android: true
  ios: true
  fullscreen: false
  android_gravity: center
  ios_content_mode: center

  android_12:
    color: "#172230"
    color_dark: "#172230"
    image: assets/splash/splash12.png
    image_dark: assets/splash/splash12.png

flutter:
  uses-material-design: true
  assets: 
    - assets/text/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Custom
      fonts:
        - asset: fonts/Light.ttf
          weight: 300
        - asset: fonts/Regular.ttf
          weight: 400
        - asset: fonts/Medium.ttf
          weight: 500
        - asset: fonts/SemiBold.ttf
          weight: 600
        - asset: fonts/Bold.ttf
          weight: 700
        - asset: fonts/ExtraBold.ttf
          weight: 800
